<img src="holder.js/100x100" class="img-rounded" />
<p><b>REQUEST</b>: <?php echo ( ! empty($this->id) ? $this->id : 'default params'); ?></p>
<p><b>Module Controller Helper</b>: <?php echo $this->modhelc; ?></p>
<p><b>Controller Helper</b>: <?php echo $this->hello; ?></p>
<p><b>Module View Helper</b>: <?php echo $this->modhelv("World"); ?></p>
<p><b>View Helper</b>: <?php echo $this->alloha("World"); ?></p>