<img src="holder.js/100x100" class="img-rounded" />
<p><b>REQUEST id</b>: <?php echo ( ! empty($this->id) ? $this->id : 'default id params'); ?></p>
<p><b>REQUEST qs</b>: <?php echo ( ! empty($this->qs) ? $this->qs : 'default qs params'); ?></p>
<p><b>Module Controller Helper</b>: <?php echo $this->modhelc; ?></p>
<p><b>Controller Helper</b>: <?php echo $this->hello; ?></p>
<p><b>Module View Helper</b>: <?php echo $this->modhelv("World"); ?></p>
<p><b>View Helper</b>: <?php echo $this->alloha("World"); ?></p>